<?php

declare(strict_types=1);

namespace Pholio;

require_once __DIR__ . '/../Exceptions.php';

/**
 * The complete lucide set, rendered the way lucide-react renders it.
 *
 * The data lives in `vendor-data/lucide/icons.json` (generated by
 * `verify/tools/build-lucide-data.mjs` from an installed lucide-react) and is
 * loaded on first use. The markup follows `buildLucideIconNode.mjs`: root
 * attributes in the order xmlns, width, height, viewBox, fill, stroke,
 * stroke-width, stroke-linecap, stroke-linejoin, class, aria-hidden; the class is
 * `lucide lucide-<name>`, then one `lucide-<alias>` class per entry in the icon's
 * `aliases`, then the extra classes, without duplicates (`mergeClasses`).
 * Alias classes belong to the icon, not to the requested name: `sidebar` and
 * `panel-left` both render `lucide lucide-panel-left lucide-sidebar`.
 *
 * Empty child elements are written as `<path …/>`; once parsed that is the same
 * DOM as `<path …></path>`.
 */
final class Icons
{
    /** Root attributes before the class, defaults from `defaultAttributes.mjs` (every icon has size 24). */
    private const HEAD = 'xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

    /** Without an aria-* attribute of its own, lucide-react sets `aria-hidden="true"`. */
    private const TAIL = 'aria-hidden="true"';

    private const DATA_FILE = __DIR__ . '/../../vendor-data/lucide/icons.json';

    /** @var array{icons:array<string,string>,classAliases:array<string,list<string>>,aliases:array<string,string>,version:string}|null */
    private static ?array $data = null;

    /**
     * One icon as SVG markup.
     *
     * $name is a lucide name in kebab-case ("triangle-alert") or an alias
     * ("sidebar", "text", "edit"). $extraClass is appended after the lucide classes.
     *
     * @throws ContentException for an unknown name, listing the closest known names
     */
    public static function svg(string $name, string $extraClass = ''): string
    {
        $data = self::data();
        $key = $data['aliases'][$name] ?? $name;
        if (!isset($data['icons'][$key])) {
            $suggestions = self::closest($name, 5);
            throw new ContentException(
                'unknown icon "' . $name . '"'
                . ($suggestions === [] ? '' : '; did you mean: ' . implode(', ', $suggestions))
                . '. Names: https://lucide.dev/icons'
            );
        }

        $tokens = ['lucide', 'lucide-' . $key];
        foreach ($data['classAliases'][$key] ?? [] as $alias) {
            $tokens[] = 'lucide-' . $alias;
        }
        foreach (explode(' ', $extraClass) as $token) {
            $tokens[] = $token;
        }

        // mergeClasses: drop empty entries, the first occurrence wins.
        $classes = [];
        foreach ($tokens as $token) {
            if (trim($token) !== '' && !in_array($token, $classes, true)) {
                $classes[] = $token;
            }
        }

        $class = htmlspecialchars(trim(implode(' ', $classes)), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

        return '<svg ' . self::HEAD . ' class="' . $class . '" ' . self::TAIL . '>' . $data['icons'][$key] . '</svg>';
    }

    /**
     * Every valid name: canonical names and aliases, sorted.
     *
     * @return list<string>
     */
    public static function names(): array
    {
        $data = self::data();
        $names = array_merge(array_keys($data['icons']), array_keys($data['aliases']));
        sort($names, SORT_STRING);

        return $names;
    }

    /**
     * At most $limit known names closest to $value by Levenshtein distance
     * (compared in lower case), ties in alphabetical order.
     *
     * @return list<string>
     */
    public static function closest(string $value, int $limit = 5): array
    {
        $needle = strtolower($value);
        $scored = [];
        foreach (self::names() as $candidate) {
            $scored[] = [levenshtein($needle, $candidate), $candidate];
        }
        usort($scored, static fn(array $a, array $b): int => $a[0] <=> $b[0] ?: strcmp($a[1], $b[1]));

        return array_map(static fn(array $entry): string => $entry[1], array_slice($scored, 0, max(0, $limit)));
    }

    /** Version of the lucide-react package the data was generated from. */
    public static function version(): string
    {
        return self::data()['version'];
    }

    /** @return array{icons:array<string,string>,classAliases:array<string,list<string>>,aliases:array<string,string>,version:string} */
    private static function data(): array
    {
        if (self::$data !== null) {
            return self::$data;
        }

        $json = @file_get_contents(self::DATA_FILE);
        if ($json === false) {
            throw new \LogicException('lucide data missing: ' . self::DATA_FILE . ' (node verify/tools/build-lucide-data.mjs)');
        }

        $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        if (!is_array($decoded) || !is_array($decoded['icons'] ?? null) || !is_array($decoded['aliases'] ?? null)
            || !is_array($decoded['classAliases'] ?? null) || !is_string($decoded['version'] ?? null)) {
            throw new \LogicException('lucide data incomplete: ' . self::DATA_FILE);
        }

        return self::$data = [
            'icons' => $decoded['icons'],
            'classAliases' => $decoded['classAliases'],
            'aliases' => $decoded['aliases'],
            'version' => $decoded['version'],
        ];
    }
}
