<?php

declare(strict_types=1);

namespace Pholio;

require_once __DIR__ . '/../Exceptions.php';
require_once __DIR__ . '/../lib/Html.php';
require_once __DIR__ . '/../lib/Ids.php';

/**
 * Tabs, rebuilt from `fumadocs-ui/dist/components/tabs.js` (`Tabs`, `Tab`) on
 * `components/ui/tabs.js` and Base UI `Tabs` (@base-ui/react 1.8.0).
 *
 * Structure as in the hydrated reference DOM:
 *   div[data-orientation][data-activation-direction]           Tabs.Root
 *     div[role=tablist]                                         Tabs.List
 *       span (only with label), button[role=tab] per item       Tabs.Tab
 *     div[role=tabpanel]                                        only the active panel
 *     template[data-nd-tabs]                                    all panels + settings
 *
 * Base UI doesn't mount inactive panels (`keepMounted` is off). So exactly one
 * panel is in the DOM; all panels are also stored in a `<template>`, from which
 * js/tabs.js creates the new panel when switching. The template also carries the
 * settings (`groupId`, `persist`, `updateAnchor`), because the reference prints
 * no attribute for them; the golden DOM comparison removes `<template>`.
 *
 * `aria-controls` appears only on the active tab: Base UI only knows the ids of
 * mounted panels (`registerMountedTabPanel`). `data-index` on the panel is the
 * index among mounted panels, so always 0.
 */

/**
 * `escapeValue` from tabs.js: lower case, and only the first whitespace
 * character becomes a hyphen (the regex has no `g`).
 */
function nd_tabs_escape(string $value): string
{
    return (string) preg_replace('/\s/u', '-', mb_strtolower($value, 'UTF-8'), 1);
}

/**
 * Tabs from `<Tabs items>`.
 *
 * @param array{items:list<string>, defaultIndex?:int, groupId?:?string, persist?:bool,
 *              updateAnchor?:bool, label?:?string} $props
 * @param list<array{value:?string, html:string}> $tabs content per `<Tab>`; `value` raw as in the source
 *        (null = position in `items`, like `useCollectionIndex`)
 */
function nd_tabs(array $props, array $tabs): string
{
    $items = $props['items'];
    $values = array_map('Pholio\nd_tabs_escape', $items);
    $defaultIndex = (int) ($props['defaultIndex'] ?? 0);
    if (!isset($values[$defaultIndex])) {
        throw new ContentException('Tabs: defaultIndex ' . $defaultIndex . ' is outside of items.');
    }

    $panels = [];
    foreach ($tabs as $position => $tab) {
        $raw = $tab['value'] ?? ($items[$position] ?? null);
        if ($raw === null) {
            throw new ContentException('Tabs: <Tab> at position ' . ($position + 1) . ' has no value and no entry in items.');
        }
        $panels[] = ['value' => nd_tabs_escape($raw), 'html' => $tab['html']];
    }

    $label = $props['label'] ?? null;
    $head = $label !== null && $label !== ''
        ? Html::tag('span', ['class' => 'nd-tabbox-label'], Html::e($label))
        : '';

    return nd_tabs_root(
        [
            'root' => 'nd-tabbox',
            'list' => 'nd-tabbox-list not-prose',
            'panel' => 'nd-tabbox-panel prose-no-margin',
        ],
        $values,
        $items,
        $values[$defaultIndex],
        $panels,
        $head,
        [
            'groupId' => $props['groupId'] ?? null,
            'persist' => (bool) ($props['persist'] ?? false),
            'updateAnchor' => (bool) ($props['updateAnchor'] ?? false),
            'guard' => true,
        ],
        static fn (bool $active): string => '',
        static fn (bool $active): string => 'nd-tabbox-trigger',
    );
}

/**
 * Tabs from consecutive code blocks with `tab="…"`:
 * `CodeBlockTabs`/`CodeBlockTabsList`/`CodeBlockTabsTrigger`/`CodeBlockTab` from
 * `fumadocs-ui/dist/components/codeblock.js`, generated by
 * `fumadocs-core/dist/mdx-plugins/remark-code-tab.js` (`generateCodeBlockTabs`).
 * The values stay unchanged (no `escapeValue`); a `tab-group` becomes
 * `groupId` + `persist`.
 *
 * @param list<array{value:string, html:string}> $panels
 */
function nd_code_tabs(string $defaultValue, ?string $groupId, array $panels): string
{
    $values = array_map(static fn (array $p): string => $p['value'], $panels);

    return nd_tabs_root(
        [
            'root' => 'nd-codetabs',
            'list' => 'nd-codetabs-list',
            'panel' => null,
        ],
        $values,
        $values,
        $defaultValue,
        $panels,
        '',
        ['groupId' => $groupId, 'persist' => $groupId !== null, 'updateAnchor' => false, 'guard' => false],
        static fn (bool $active): string => Html::tag('div', ['class' => 'nd-codetabs-indicator']),
        static fn (bool $active): string => 'nd-codetabs-trigger',
    );
}

/**
 * Structure shared by both variants.
 *
 * @param array{root:string, list:string, panel:?string} $classes
 * @param list<string> $values   tab values in order
 * @param list<string> $labels   tab labels (unescaped)
 * @param list<array{value:string, html:string}> $panels
 * @param array{groupId:?string, persist:bool, updateAnchor:bool, guard:bool} $config
 * @param callable(bool):string $triggerPrefix markup before the label
 * @param callable(bool):string $triggerClass
 */
function nd_tabs_root(
    array $classes,
    array $values,
    array $labels,
    string $selected,
    array $panels,
    string $head,
    array $config,
    callable $triggerPrefix,
    callable $triggerClass,
): string {
    $state = ['data-orientation' => 'horizontal', 'data-activation-direction' => 'none'];

    $tabIds = [];
    foreach ($values as $index => $value) {
        $tabIds[$index] = Ids::next();
    }

    $panelIds = [];
    foreach ($panels as $index => $panel) {
        $panelIds[$index] = Ids::next();
    }

    $activePanel = null;
    foreach ($panels as $index => $panel) {
        if ($panel['value'] === $selected) {
            $activePanel = $index;
            break;
        }
    }

    $buttons = $head;
    foreach ($values as $index => $value) {
        $active = $value === $selected;
        $buttons .= Html::tag('button', [
            'type' => 'button',
            'data-active' => $active,
            ...$state,
            'aria-disabled' => 'false',
            'tabindex' => $active ? '0' : '-1',
            'role' => 'tab',
            'aria-selected' => $active ? 'true' : 'false',
            'id' => $tabIds[$index],
            'data-composite-item-active' => $active,
            'aria-controls' => $active && $activePanel !== null ? $panelIds[$activePanel] : null,
            'class' => $triggerClass($active),
        ], $triggerPrefix($active) . Html::e($labels[$index]));
    }

    $out = Html::tag('div', [...$state, 'role' => 'tablist', 'class' => $classes['list']], $buttons);

    $tabIdFor = static function (string $value) use ($values, $tabIds): ?string {
        $index = array_search($value, $values, true);

        return $index === false ? null : $tabIds[$index];
    };

    if ($activePanel !== null) {
        $out .= Html::tag('div', [
            ...$state,
            'id' => $panelIds[$activePanel],
            'role' => 'tabpanel',
            'tabindex' => '0',
            'data-index' => '0',
            'class' => $classes['panel'],
            'aria-labelledby' => $tabIdFor($panels[$activePanel]['value']),
        ], $panels[$activePanel]['html']);
    }

    $stored = '';
    foreach ($panels as $index => $panel) {
        $stored .= Html::tag('div', [
            'data-value' => $panel['value'],
            'id' => $panelIds[$index],
            'class' => $classes['panel'],
        ], $panel['html']);
    }

    $out .= Html::tag('template', [
        'data-nd-tabs' => true,
        'data-values' => (string) json_encode($values, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR),
        'data-default' => $selected,
        'data-group-id' => $config['groupId'],
        'data-persist' => $config['persist'],
        'data-update-anchor' => $config['updateAnchor'],
        'data-guard' => $config['guard'],
    ], $stored);

    return Html::tag('div', [...$state, 'class' => $classes['root']], $out);
}
