<?php

declare(strict_types=1);

namespace Pholio;

/**
 * What a server sends so that agents find the Markdown and the indexes, in one
 * place for the three servers Pholio knows:
 *
 * - the generated `.htaccess` (Htaccess) for Apache,
 * - the `_headers` file for Cloudflare Pages, Netlify and Workers static assets,
 * - `pholio dev` (DevServer.php), which reads that `_headers` file.
 *
 * On every response, 404s included: a `Link` header with the discovery documents
 * that the build writes (llms.txt, llms-full.txt, the agent card, the skills
 * index), `X-Llms-Txt`, and `Vary: Accept, User-Agent` when pages have Markdown
 * twins. Content negotiation: a page is answered with its twin for
 * `Accept: text/markdown` or an AI assistant's user agent, and as text/plain for
 * `Accept: text/plain`. Static hosts with `_headers` only get the headers; the
 * negotiation needs an edge function there (examples/cloudflare-worker).
 */
final class AgentHeaders
{
    /** User agents of AI assistants fetching a page on a user's behalf; they get the Markdown twin. */
    public const USER_AGENTS = [
        'Claude-User', 'ChatGPT-User', 'OAI-SearchBot', 'PerplexityBot', 'Perplexity-User',
        'Google-Agent', 'MistralAI-User', 'DuckAssistBot', 'cohere-ai',
    ];

    public const FILE = '_headers';

    /**
     * The headers for every response, in order. Empty when `agents.headers` is off.
     *
     * @param array<string,mixed> $config normalised
     * @return list<array{0:string, 1:string}> name, value
     */
    public static function headers(array $config): array
    {
        $agents = $config['agents'];
        if (!$agents['headers']) {
            return [];
        }
        $home = rtrim($config['homeUrl'], '/');

        $links = [];
        if ($agents['llmsTxt']) {
            $links[] = '<' . $home . '/llms.txt>; rel="llms-txt"';
        }
        if ($agents['llmsFullTxt']) {
            $links[] = '<' . $home . '/llms-full.txt>; rel="llms-full-txt"';
        }
        if ($agents['agentCard'] && $config['site']['url'] !== null) {
            $links[] = '<' . $home . '/.well-known/agent-card.json>; rel="agent-card"';
        }
        if ($agents['skill']) {
            $links[] = '<' . $home . '/.well-known/agent-skills/index.json>; rel="agent-skills"';
        }

        $out = [];
        if ($links !== []) {
            $out[] = ['Link', implode(', ', $links)];
        }
        if ($agents['llmsTxt']) {
            $out[] = ['X-Llms-Txt', $home . '/llms.txt'];
        }
        if ($agents['markdown']) {
            $out[] = ['Vary', 'Accept, User-Agent'];
        }

        return $out;
    }

    /** Whether the server answers pages with their Markdown twin. */
    public static function negotiates(array $config): bool
    {
        return $config['agents']['headers'] && $config['agents']['markdown'];
    }

    /**
     * The `_headers` file, or null when there are no headers to send.
     *
     * @param array<string,mixed> $config normalised
     */
    public static function file(array $config): ?string
    {
        $headers = self::headers($config);
        if ($headers === []) {
            return null;
        }
        $home = rtrim($config['homeUrl'], '/');
        $block = implode("\n", array_map(static fn(array $h): string => '  ' . $h[0] . ': ' . $h[1], $headers));

        $out = "# Generated by Pholio. Do not edit.\n"
            . "# Response headers for Cloudflare Pages, Netlify and Cloudflare Workers static assets.\n"
            . "# Serving the Markdown twin for \"Accept: text/markdown\" needs an edge function on these hosts.\n";
        foreach ($home === '' ? ['/*'] : [$home, $home . '/*'] as $pattern) {
            $out .= $pattern . "\n" . $block . "\n";
        }

        return rtrim($out);
    }

    /**
     * Which twin a request asks for: "markdown", "plain" or null for the HTML page.
     */
    public static function negotiate(string $accept, string $userAgent): ?string
    {
        if (stripos($accept, 'text/markdown') !== false || preg_match('/' . self::userAgentPattern() . '/i', $userAgent) === 1) {
            return 'markdown';
        }

        return stripos($accept, 'text/plain') !== false ? 'plain' : null;
    }

    /** The user agents as a regular expression alternation, valid in PCRE and Apache. */
    public static function userAgentPattern(): string
    {
        return implode('|', array_map(static fn(string $agent): string => preg_quote($agent, '/'), self::USER_AGENTS));
    }
}
